<a href="https://colab.research.google.com/github/enababac1-png/repo_1/blob/main/Predavanje1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 dio
predavanje

In [1]:
12

12

In [4]:
type(12.5)

float

In [5]:
type(12)

int

In [6]:
type("Ena")

str

In [7]:
'apple'

'apple'

In [8]:
True

True

In [9]:
False

False

In [10]:
3<5

True

In [11]:
7<2

False

In [12]:
type(True)

bool

In [ ]:
dictionaries {}
list []
tuple ()

In [13]:
[1,2,3]

[1, 2, 3]

In [14]:
type([1,2,3])

list

In [15]:
t = [1, 2, 3]

In [16]:
t

[1, 2, 3]

In [17]:
plants = {"apple":"a fruit", "banana":"a herb"}

In [18]:
type({"apple":"a fruit", "banana":"a herb"})

dict

In [19]:
plants

{'apple': 'a fruit', 'banana': 'a herb'}

In [20]:
plants['banana']

'a herb'

In [21]:
import pandas as pd

In [22]:
pd.DataFrame(plants, [0,1])

apple  banana
0  a fruit  a herb
1  a fruit  a herb

In [24]:
squares = [1, 4, 9, 16, 25]

In [27]:
type(squares)

list

In [26]:
squares

[1, 4, 9, 16, 25]

In [28]:
squares[4]

25

In [29]:
squares [-2]

16

In [30]:
squares [:]

[1, 4, 9, 16, 25]

In [32]:
squares [1:]

[4, 9, 16, 25]

In [33]:
squares [1:3]

[4, 9]

In [34]:
squares [-2:]

[16, 25]

In [35]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [36]:
squares

[1, 4, 9, 16, 25]

In [38]:
sq2 = squares + [36, 49, 64, 81, 100]

In [39]:
sq2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [40]:
animals = ['cat', 'dog', 'bird']

In [41]:
animals [0]

'cat'

In [42]:
len (sq2)

10

In [43]:
len(sq2[:5])

5

In [63]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [65]:
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [67]:
letters[1:2] = [1, 2, 3, 4, 5]

In [68]:
letters

['a', 1, 2, 3, 4, 5, 2, 3, 4, 5, 'c', 'd', 'e', 'f', 'g']

In [69]:
len(letters)

15

In [50]:
abs (1)

1

In [51]:
abs (-10)

10

In [59]:
import operator

In [60]:
1+3

4

In [61]:
operator.add(1, 3)

4

In [71]:
operator.sub(1, 10)

-9

In [72]:
operator.eq(1, 10)

False

In [73]:
operator.eq(10,10)

True

print

In [74]:
print (1)

1


In [79]:
print('This' +' '+ 'is' +' ' +'a'+ ' '+ 'full' +' '+ 'sentence')

This is a full sentence


In [80]:
print ('Michael', 'is', 'helping')

Michael is helping


In [81]:
print (sq2[1:5])

[4, 9, 16, 25]


In [82]:
sq2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [87]:
None

In [88]:
type(None)

NoneType

funkcije

In [89]:
def our_function(x):
  '''This function multiple its argument by 2.
  Writen by Ena'''
  result = x*2
  return result


In [90]:
our_function(5)

10

In [92]:
our_function(3.14)

6.28

In [93]:
type(our_function)

function

In [94]:
import math

In [95]:
def ph(C):
  '''This function calculates the pH of a solution.
  It uses the concentration of the H+ in mol/L.
  It returns the pH.'''
  ph_value = -math.log10(C)
  return ph_value

In [98]:
ph(0.001)

3.0

In [100]:
def ph1(c):
  return -math.log10(c)

In [101]:
ph1(0.001)

3.0

In [112]:
def task(x,y):
  '''definicija'''
  print('This is the log10 of x', math.log10(x))
  print('This is the log10 of y', math.log10(y))
  new_number = math.log10(x) + math.log(y)
  print('The result is below:')
  return new_number

In [113]:
task(1000, 2.73)

This is the log10 of x 3.0
This is the log10 of y 0.436162647040756
The result is below:


4.004301609196869

In [111]:
def konv_eur(euro):
  dkk = euro*7.55
  return dkk

In [114]:
konv_eur(10)

75.5

In [117]:
def plus(a, b, c, d):
  suma = a + b + c + d
  return suma

In [118]:
plus (3, 4, 5, 6)

18

In [120]:
plus (3, 4, 100, 1000)

1107

= i ==

In [121]:
1==1

True

In [123]:
k= (1, 2, 3)

In [124]:
type(k)

tuple

In [125]:
width = 20
height = 5 + 90
height, width


(95, 20)

In [129]:
width == 30

True

In [130]:
width == 20

False

In [128]:
width = 30

In [133]:
cp1 = 'Tomo'
cp2 = 'Maria'
cp1, cp2

('Tomo', 'Maria')

In [134]:
width ==height

False

In [135]:
width = height

In [136]:
width

95

In [137]:
cp1 == cp2

False

In [139]:
cp1 != cp2

True

is and is not

In [140]:
5 is 4

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-171648558.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 4


False

In [141]:
5 is 5

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-1783323536.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 5


True

In [142]:
width is height

True

In [143]:
width is not height

False

liste

In [144]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

In [147]:
squares.append(36)

In [148]:
squares

[1, 4, 9, 16, 25, 36, 36, 36]

In [149]:
new_list.append(49)

NameError: name 'new_list' is not defined

In [150]:
last_list = squares.copy()
last_list

[1, 4, 9, 16, 25, 36, 36, 36]

In [151]:
squares.append(10)
last_list

[1, 4, 9, 16, 25, 36, 36, 36]

In [152]:
squares

[1, 4, 9, 16, 25, 36, 36, 36, 10]

In [154]:
print ('Participants in the course were', cp1, 'and', cp2,'.')

Participants in the course were Tomo and Maria .


In [156]:
print('Participants in the course were %s and %s.'
      %(cp1, cp2))

Participants in the course were Tomo and Maria.


In [160]:
sample = 'u553'
conc = 0.016

print ('In a sample %s we found %s mg/L of drugs' %(sample, conc))

In a sample u553 we found 0.016 mg/L of drugs


In [161]:
print(f'In a sample {sample} we found {conc} mg/L of drugs.')

In a sample u553 we found 0.016 mg/L of drugs.


In [162]:
def bmi (w, h):
  bmi = w/h**2
  return bmi

In [164]:
bmi(w=60, h=1.69)

21.007667798746546

c1 * V1 = c2 *V2

In [171]:
def diluter (c1, v1=1, v2=2):
  '''Calculating dilution
  returns c2'''
  c2 = c1*v1/v2
  return c2

In [172]:
diluter(0.5, 1, 2)

0.25

In [173]:
help(diluter)

Help on function diluter in module __main__:

diluter(c1, v1=1, v2=2)
    Calculating dilution
    returns c2



In [174]:
diluter(2)

1.0

In [175]:
diluter(2, 1, 3)

0.6666666666666666

In [176]:
def factor_corrections(c, f=1):
  conc = c*f
  return conc

In [178]:
factor_corrections (0.0002)

0.0002

In [192]:
def do_something_else (a=1, b=2, c=3):
  return (a, b, c)

In [187]:
do_something_else ()

(1, 2, 3)

In [193]:
do_something_else (10,10)

(10, 10, 3)

In [194]:
do_something_else(5, 5, c=5)

(5, 5, 5)

In [195]:
do_something_else (a=10)

(10, 2, 3)

In [197]:
def suma(a,b):
  return a + b

def adding_3rd(a, b, c):
  return suma(a, b) + c

adding_3rd(1, 2, 3)

6

for

In [200]:
my_friends = ['Michael', 'Tomo', 'Maria', 'Peter']

In [201]:
for person in my_friends:
  print (person)

Michael
Tomo
Maria
Peter


In [203]:
wights = [80, 90, 55, 70]
heights = [1.8, 2.0, 1.6, 1.55]

for x, friend in enumerate(my_friends):
  bmi_person = bmi(wights[x], heights[x])

  print(f'{friend} has the bmi of {bmi_person}.')


Michael has the bmi of 24.691358024691358.
Tomo has the bmi of 22.5.
Maria has the bmi of 21.484374999999996.
Peter has the bmi of 29.1363163371488.


In [204]:
  print(f'{friend} has the bmi of {bmi_person}.')

Peter has the bmi of 29.1363163371488.


In [205]:
bmi_person

29.1363163371488

In [206]:
squares = [1, 4, 9, 16, 25]

In [207]:
for x in squares:
  print('Element is %s' %x)

Element is 1
Element is 4
Element is 9
Element is 16
Element is 25


In [208]:
for number in squares:
  print(number)

1
4
9
16
25


In [210]:
course_participants = [cp1, cp2]

In [211]:
course_participants

['Tomo', 'Maria']

In [212]:
for name in course_participants:
  print(name)

Tomo
Maria


In [213]:
for pos in range (len(course_participants)):
  print(pos)

0
1


In [214]:
for number, element in enumerate(squares):
  print(number, element)

0 1
1 4
2 9
3 16
4 25


In [ ]:
import math

In [215]:
for number in squares:
  sq_root = math.sqrt(number)
  print(sq_root)

1.0
2.0
3.0
4.0
5.0


if else

In [216]:
1<=2

True

In [218]:
if 1==1:
  print('yes')
  print('da')
  print('YEAA BABY')

yes
da
YEAA BABY


In [219]:
1==2

False

In [220]:
cp1 = 'Mila'
cp2 = 'Marko'

In [224]:
if cp1 == cp2:
  print('da')

In [225]:
if cp1 != cp2:
  print('da')

da


In [226]:
if cp1 == cp2:
  print('da')
else:
  print('ne')

ne


In [227]:
def check_gender_by_name(name):
  if name[-1] == "a":
    gender = "female"
  elif name[-1] == "o":
    gender = "male"
  else:
    gender = "unknown"
  return gender

In [228]:
check_gender_by_name('Lan')

'unknown'

In [229]:
check_gender_by_name('Marko')

'male'

In [230]:
check_gender_by_name('Ena')

'female'

In [235]:
import math

In [236]:
def ph(c):
  return -m.log10(c)

In [237]:
ph(0.001)

3.0

In [240]:
def ph_evaluator(c=0.001):
  '''Ph decision maker'''
  ph_value = ph(c)

  if ph_value < 7:
    decision = 'kiselo'
  else:
    decision = 'lužnato'

  return decision


ph_evaluator()

'kiselo'

In [250]:
def ph_evaluator(c=0.001):
  if ph(c) < 7:
    return 'kiselo'
  else:
    return 'lužnato'


conc_list = [0.001, 0.01, 0.1, 1, 10]
for solution in conc_list:
    print(ph_evaluator(solution))

kiselo
kiselo
kiselo
kiselo
kiselo


In [245]:
def test_if_else(a, b):
  '''
  a, b su argumenti
  return 'a > b' or 'a is not > b'
  '''

  if a > b:
      print(a, ' > ', b)
  else:
      print('%d is not > %d' %(a, b))

In [255]:
help(test_if_else)



Help on function test_if_else in module __main__:

test_if_else(a, b)
    a, b su argumenti
    return 'a > b' or 'a is not > b'



In [256]:
test_if_else(6, 2)

6  >  2


In [257]:
test_if_else(2, 6)

2 is not > 6


In [258]:
test_if_else(2, 'Lana')

TypeError: '>' not supported between instances of 'int' and 'str'

In [260]:
def rectangle_area(a,b):
  '''dokumentacija'''

  A = a*b
  if a == b:
    print('kvadrat')
  else:
    print('pravokutnik')
  return A

In [261]:
rectangle_area(2, 3)

pravokutnik


6

In [262]:
for letter in [1, 2, 3]:
  print('broj: ', letter)

broj:  1
broj:  2
broj:  3


In [263]:
x=5

In [266]:
x

7

In [265]:
x = 7

In [267]:
y = 2

In [268]:
x + y

9

In [270]:
povrsina = rectangle_area(5, 4)



pravokutnik


In [271]:
povrsina

20

In [272]:
-(3**4)

-81

In [273]:
3* 3.75 / 1.5

7.5

In [274]:
a = [4, 5, 6]
n = [1, 2, 3]

In [276]:
x = [a, n]

In [277]:
x

[[4, 5, 6], [1, 2, 3]]

In [278]:
import numpy as np

In [280]:
nums1 = [1, 2, 3, 4, 5]
nums1

[1, 2, 3, 4, 5]

In [281]:
nums2 = np.array(nums1)
nums2

array([1, 2, 3, 4, 5])

In [282]:
type(nums1), type(nums2)

(list, numpy.ndarray)

In [283]:
max(nums1)

5

In [284]:
min(nums1)

1

In [285]:
np.min(nums1)

np.int64(1)

In [287]:
x1 = np.array([1.3, 0, 2])
x1

array([1.3, 0. , 2. ])

In [288]:
x2 = np.array([1, 0, 2])
x2

array([1, 0, 2])

In [289]:
type(x1), type(x2)

(numpy.ndarray, numpy.ndarray)

In [290]:
x1.dtype

dtype('float64')

In [291]:
x2.dtype

dtype('int64')

In [293]:
x2 = np.arange(20, 50, 2)
x2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [295]:
np.linspace(10, 20, 10, endpoint=False)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [296]:
nule = np.zeros((5,3))
nule.shape

(5, 3)

In [297]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [298]:
x4 = np.random.random((3, 10))
x4

array([[0.94240993, 0.95566048, 0.81198808, 0.07211908, 0.44842163,
        0.58601577, 0.22788579, 0.05603073, 0.05216833, 0.22168741],
       [0.07601117, 0.60611908, 0.25052645, 0.02127087, 0.8937193 ,
        0.5410348 , 0.82886743, 0.53277059, 0.68427924, 0.84095888],
       [0.99954463, 0.43190156, 0.45309141, 0.28908546, 0.82128251,
        0.60104549, 0.88413336, 0.87477768, 0.76507203, 0.16868381]])

In [300]:
import pandas as pd

In [301]:
pd.DataFrame(x4)

0         1         2         3         4         5         6  \
0  0.942410  0.955660  0.811988  0.072119  0.448422  0.586016  0.227886   
1  0.076011  0.606119  0.250526  0.021271  0.893719  0.541035  0.828867   
2  0.999545  0.431902  0.453091  0.289085  0.821283  0.601045  0.884133   

          7         8         9  
0  0.056031  0.052168  0.221687  
1  0.532771  0.684279  0.840959  
2  0.874778  0.765072  0.168684

In [302]:
x4.dtype

dtype('float64')

In [303]:
x4.shape

(3, 10)

In [304]:
x4.reshape(10,3)

array([[0.94240993, 0.95566048, 0.81198808],
       [0.07211908, 0.44842163, 0.58601577],
       [0.22788579, 0.05603073, 0.05216833],
       [0.22168741, 0.07601117, 0.60611908],
       [0.25052645, 0.02127087, 0.8937193 ],
       [0.5410348 , 0.82886743, 0.53277059],
       [0.68427924, 0.84095888, 0.99954463],
       [0.43190156, 0.45309141, 0.28908546],
       [0.82128251, 0.60104549, 0.88413336],
       [0.87477768, 0.76507203, 0.16868381]])

In [305]:
x4.T

array([[0.94240993, 0.07601117, 0.99954463],
       [0.95566048, 0.60611908, 0.43190156],
       [0.81198808, 0.25052645, 0.45309141],
       [0.07211908, 0.02127087, 0.28908546],
       [0.44842163, 0.8937193 , 0.82128251],
       [0.58601577, 0.5410348 , 0.60104549],
       [0.22788579, 0.82886743, 0.88413336],
       [0.05603073, 0.53277059, 0.87477768],
       [0.05216833, 0.68427924, 0.76507203],
       [0.22168741, 0.84095888, 0.16868381]])

In [306]:
np.arange(2, 20).reshape(2, 3, 3).T

array([[[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]],

       [[ 4, 13],
        [ 7, 16],
        [10, 19]]])

In [312]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [310]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [313]:
I@A

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [314]:
A@A

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])